# Generated by Django 5.2.10 on 2026-01-25 18:44

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioTask",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("original_file", models.FileField(upload_to="input_audio/%Y/%m/%d/")),
                ("processed_file", models.FileField(blank=True, null=True, upload_to="output_audio/%Y/%m/%d/")),
                ("hidden_message", models.TextField(blank=True, null=True)),
                (
                    "task_type",
                    models.CharField(
                        choices=[("ENCODE", "Encode"), ("DECODE", "Decode")], default="ENCODE", max_length=10
                    ),
                ),
                (
                    "task_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("ERROR", "Error"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
